In [21]:
import numpy as np
arr1=np.array(42)
print(arr1)


42


In [53]:
import numpy as np
arr2=np.array([1,2,3,4,5])
print(arr2)

print(arr2[2:5])

[1 2 3 4 5]
[3 4 5]


In [25]:
import numpy as np
arr3=np.array([[1,2,3],[4,5,6]])
print(arr3)

[[1 2 3]
 [4 5 6]]


In [27]:
import numpy as np
arr4=np.array([[13,14,15],[16,17,18]])
print(arr4)

[[13 14 15]
 [16 17 18]]


In [29]:
import numpy as np
arr5=np.array([[[100,101,102],[103,104,105]],[[106,107,108],[109,110,111]]])
print(arr5)

[[[100 101 102]
  [103 104 105]]

 [[106 107 108]
  [109 110 111]]]


In [31]:
print(arr1.ndim)

0


In [33]:
print(arr2.ndim)

1


In [35]:
print(arr3.ndim)

2


In [37]:
print(arr4.ndim)

2


In [39]:
print(arr5.ndim)

3


In [41]:
import numpy as np
arr=np.array
arr=np.array([1,2,3,4,5])
print(arr[0])

1


In [43]:
import numpy as np
arr=np.array([[13,14,15,16],[17,18,19,20]])
print(arr[1,3])

20


In [45]:
print(arr[0,2])

15


In [47]:
print(arr5[1,1,2])

111


In [49]:
import numpy as np
arr=np.array([[[33,34,35],[36,37,38]],[[43,44,45],[46,47,48]]])
print(arr[1,1,2])

48


In [51]:
print(arr[0,1,1])

37


In [55]:
print(arr1.shape)

()


In [57]:
print(arr2.shape)

(5,)


In [59]:
print(arr3.shape)

(2, 3)


In [61]:
print(arr4.shape)

(2, 3)


In [63]:
print(arr5.shape)

(2, 2, 3)


In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,
              